# Generated by Django 3.2.8 on 2021-11-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('1', 'Luz'), ('2', 'Agua'), ('3', 'Mantenimiento')], max_length=1, verbose_name='servicios')),
                ('monto', models.IntegerField(verbose_name='Monto')),
                ('mora', models.IntegerField(verbose_name='Mora')),
                ('monto_total', models.IntegerField(verbose_name='Monto total')),
            ],
        ),
    ]
