# Generated by Django 3.2.8 on 2021-11-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='servicio',
            field=models.CharField(choices=[('Luz', 'Luz'), ('Agua', 'Agua'), ('Mantenimiento', 'Mantenimiento')], max_length=20, verbose_name='servicios'),
        ),
    ]
