# Generated by Django 3.2.8 on 2021-11-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_servicio_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='monto_total',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='mora',
        ),
        migrations.AddField(
            model_name='servicio',
            name='estado',
            field=models.CharField(default=2, max_length=20, verbose_name='estado'),
            preserve_default=False,
        ),
    ]
