# Generated by Django 3.2.8 on 2021-11-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_auto_20211111_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default=2, max_length=20, verbose_name='Mes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Adeudado', 'Adeudado')], max_length=20, verbose_name='Estado'),
        ),
    ]
