# Generated by Django 3.2.8 on 2021-11-12 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20211111_2347'),
        ('servicio', '0005_auto_20211112_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
