# Generated by Django 3.2.8 on 2021-11-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_alter_servicio_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='year',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032')], default=2, max_length=10, verbose_name='Año'),
            preserve_default=False,
        ),
    ]
