# Generated by Django 3.2.8 on 2022-01-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_servicio_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='fecha_cancelacion',
            field=models.CharField(blank=True, default='-', max_length=20, verbose_name='fecha cancelacion'),
        ),
    ]
