# Generated by Django 3.2.8 on 2021-11-12 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20211031_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='servicio',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
