# Generated by Django 3.2.8 on 2021-11-12 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0003_auto_20211111_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='users',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
