# Generated by Django 3.2.8 on 2021-10-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Material')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('stock_actual', models.IntegerField(verbose_name='Stock')),
            ],
        ),
    ]
