# Generated by Django 3.2.8 on 2021-11-01 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(verbose_name='fecha reserva')),
                ('espacio', models.CharField(choices=[('1', 'Piscina'), ('2', 'Área parrilla'), ('3', 'Sala star'), ('4', 'Área recreativa')], max_length=20, verbose_name='Espacio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
