# Generated by Django 3.2.8 on 2021-11-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='espacio',
            field=models.CharField(choices=[('Piscina', 'Piscina'), ('Área parrilla', 'Área parrilla'), ('Sala star', 'Sala star'), ('Área recreativa', 'Área recreativa')], max_length=20, verbose_name='Espacio'),
        ),
    ]
