# Generated by Django 3.2.8 on 2021-11-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_alter_actividades_espacio'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Pasado', 'Pasado')], default=1, max_length=10, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividades',
            name='hora_reserva',
            field=models.CharField(choices=[('5', '05 am'), ('6', '06 am'), ('7', '07 am'), ('8', '08 am'), ('9', '09 am'), ('10', '10 am'), ('11', '11 am'), ('12', '12 pm'), ('13', '01 pm'), ('14', '02 pm'), ('15', '03 pm'), ('16', '04 pm'), ('17', '05 pm'), ('18', '06 pm'), ('19', '07 pm'), ('20', '08 pm'), ('21', '09 pm'), ('22', '10 pm'), ('23', '11 pm'), ('24', '12 am'), ('1', '01 am'), ('2', '02 am'), ('3', '03 am'), ('4', '04 am')], default=1, max_length=4, verbose_name='Hora'),
            preserve_default=False,
        ),
    ]
