# Generated by Django 3.2.8 on 2021-11-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_auto_20211118_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='hora_reserva',
            field=models.CharField(choices=[('05 am', '05 am'), ('06 am', '06 am'), ('07 am', '07 am'), ('08 am', '08 am'), ('09 am', '09 am'), ('10 am', '10 am'), ('11 am', '11 am'), ('12 pm', '12 pm'), ('01 pm', '01 pm'), ('02 pm', '02 pm'), ('03 pm', '03 pm'), ('04 pm', '04 pm'), ('05 pm', '05 pm'), ('06 pm', '06 pm'), ('07 pm', '07 pm'), ('08 pm', '08 pm'), ('09 pm', '09 pm'), ('10 pm', '10 pm'), ('11 pm', '11 pm'), ('12 am', '12 am'), ('1 am', '01 am'), ('2 am', '02 am'), ('3 am', '03 am'), ('4 am', '04 am')], max_length=10, verbose_name='Hora'),
        ),
    ]
