# Generated by Django 3.2.8 on 2021-11-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_auto_20211125_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='fecha_reserva',
            field=models.DateField(verbose_name='fecha reserva'),
        ),
    ]
