# Generated by Django 3.2.8 on 2021-11-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_auto_20211031_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo_mantenimiento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=60, verbose_name='Descripción'),
        ),
    ]
