# Generated by Django 3.2.8 on 2021-12-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_trabajo_mantenimiento_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externos',
            old_name='trabajo_mantenimiento',
            new_name='trabajo_mantenimientos',
        ),
    ]
