# Generated by Django 3.2.8 on 2022-01-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_rename_trabajo_mantenimiento_externos_trabajo_mantenimientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo_mantenimiento',
            name='nro_departamento',
            field=models.IntegerField(blank=True, default=2, verbose_name='nro departamento'),
            preserve_default=False,
        ),
    ]
