# Generated by Django 3.2.8 on 2021-10-31 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField(verbose_name='fecha de visita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Visitantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_visita', models.IntegerField(verbose_name='Dni')),
                ('nombre_visita', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_visita', models.CharField(max_length=50, verbose_name='Apellido')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visita.visita')),
            ],
        ),
    ]
