# Generated by Django 3.2.8 on 2021-11-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='fecha_visita',
            field=models.DateField(verbose_name='fecha de visita'),
        ),
        migrations.AlterField(
            model_name='visitantes',
            name='apellido_visita',
            field=models.CharField(max_length=50, verbose_name='Apellido visitante'),
        ),
        migrations.AlterField(
            model_name='visitantes',
            name='dni_visita',
            field=models.IntegerField(verbose_name='Dni visitante'),
        ),
        migrations.AlterField(
            model_name='visitantes',
            name='nombre_visita',
            field=models.CharField(max_length=50, verbose_name='Nombre vistante'),
        ),
    ]
