# Generated by Django 3.2.8 on 2021-11-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0002_auto_20211031_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='nro_personas',
            field=models.IntegerField(default=2, verbose_name='Nro de personas'),
            preserve_default=False,
        ),
    ]
