# Generated by Django 3.2.8 on 2021-12-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0003_visita_nro_personas'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='estado',
            field=models.CharField(blank=True, default='Pendiente', max_length=30),
        ),
    ]
