# Generated by Django 3.2.8 on 2021-10-31 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_empledo', models.IntegerField(verbose_name='Dni')),
                ('nombre_empleado', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos_empleado', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('funcion', models.CharField(max_length=50, verbose_name='Funcion')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('materiales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador')),
            ],
        ),
    ]
