# Generated by Django 3.2.8 on 2021-11-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='funcion',
            field=models.CharField(choices=[('1', 'Personal limpieza'), ('2', 'Vigilante'), ('3', 'Conserje'), ('4', 'Recepcionista')], max_length=50, verbose_name='Funcion'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
